# Test your FastAPI endpoints

GET http://127.0.0.1:8000/PortaleStudenti/api_profilo_aa_scuola_tipo_cdl_pd.php
Accept: application/json

###

GET https://uniud-timetable-app.herokuapp.com/PortaleStudenti/api_profilo_aa_scuola_tipo_cdl_pd.php
Accept: application/json
